/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conversor;

import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author Sergio.Luna
 */
public class ConversorGenerico extends javax.swing.JFrame {
    
    private boolean convertirValor1Valor2;
    private final List<Conversor> conversores = new ArrayList<>();
    private Conversor conversorSeleccionado;
    
    
    /**
     * Creates new form ConversorGenerico
     */
    public ConversorGenerico() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        conversores.add(new ConvertirMetrosCentimetros());
        conversores.add(new ConvertirCelsiusFahrenheit());
        conversores.add(new ConvertirDolarPeso());
        conversores.add(new ConvertirGigabyteMegabyte());
        conversores.add(new ConvertirHorasMinutos());
        
        
        for (Conversor conversor : conversores) {
            jComboBox1.addItem(conversor.toString());
        }
        
        conversorSeleccionado = conversores.get(0);
        
        label1.setText(conversorSeleccionado.getLabelValor1());
        label2.setText(conversorSeleccionado.getLabelValor2());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        textField1 = new javax.swing.JTextField();
        textField2 = new javax.swing.JTextField();
        label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanelExit = new javax.swing.JPanel();
        jLabelExit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(32, 32, 32));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setBackground(new java.awt.Color(50, 50, 50));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        bg.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 54, 300, -1));

        textField1.setBackground(new java.awt.Color(59, 59, 59));
        textField1.setForeground(new java.awt.Color(255, 255, 255));
        textField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textField1FocusLost(evt);
            }
        });
        textField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textField1KeyPressed(evt);
            }
        });
        bg.add(textField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 147, 300, -1));

        textField2.setBackground(new java.awt.Color(59, 59, 59));
        textField2.setForeground(new java.awt.Color(255, 255, 255));
        textField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textField2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textField2FocusLost(evt);
            }
        });
        textField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textField2KeyPressed(evt);
            }
        });
        bg.add(textField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 238, 300, -1));

        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Metros");
        bg.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 125, -1, -1));

        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setText("Centimetros");
        bg.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 216, -1, -1));

        jButton1.setBackground(new java.awt.Color(50, 50, 50));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Convertir");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        bg.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 315, 353, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Conversor");
        bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jPanelExit.setBackground(new java.awt.Color(32, 32, 32));
        jPanelExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanelExitMouseExited(evt);
            }
        });

        jLabelExit.setForeground(new java.awt.Color(255, 255, 255));
        jLabelExit.setText("X");

        javax.swing.GroupLayout jPanelExitLayout = new javax.swing.GroupLayout(jPanelExit);
        jPanelExit.setLayout(jPanelExitLayout);
        jPanelExitLayout.setHorizontalGroup(
            jPanelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelExitLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabelExit, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelExitLayout.setVerticalGroup(
            jPanelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelExitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelExit)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        bg.add(jPanelExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 40, 30));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textField1FocusLost
        reconocerTextField1();
    }//GEN-LAST:event_textField1FocusLost

    

    private void textField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textField2FocusLost
        reconocerTextField2();
    }//GEN-LAST:event_textField2FocusLost

    private void reconocerTextField1() {
        convertirValor1Valor2 = true;
    }
    
    private void reconocerTextField2() {
        convertirValor1Valor2 = false;
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        convertirValores();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void convertirValores() throws HeadlessException {
        Double resultado = 0.0;
        
        if(convertirValor1Valor2){
            try {
                resultado = conversorSeleccionado.convertirValor1Valor2(Double.valueOf( textField1.getText().replace(",",".") ));
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Error al convertir", "Error", JOptionPane.ERROR_MESSAGE);
            }
            textField2.setText(String.format("%.2f", resultado));
            
        }else{
            
            try {
                resultado = conversorSeleccionado.convertirValor2Valor1(Double.valueOf( textField2.getText().replace(",",".") ));
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Error al convertir", "Error", JOptionPane.ERROR_MESSAGE);
            }
            textField1.setText(String.format("%.2f", resultado));
        }
    }

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        
        conversorSeleccionado = conversores.get(jComboBox1.getSelectedIndex());
        
        label1.setText(conversorSeleccionado.getLabelValor1());
        label2.setText(conversorSeleccionado.getLabelValor2());
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void textField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField2KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            convertirValores();
        }
        
    }//GEN-LAST:event_textField2KeyPressed

    private void textField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textField1KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            convertirValores();
        }
    }//GEN-LAST:event_textField1KeyPressed

    private void textField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textField1FocusGained
        reconocerTextField1();
    }//GEN-LAST:event_textField1FocusGained

    private void textField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textField2FocusGained
        reconocerTextField2();
    }//GEN-LAST:event_textField2FocusGained

    private void jPanelExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelExitMouseEntered
        jPanelExit.setBackground(Color.red);
    }//GEN-LAST:event_jPanelExitMouseEntered

    private void jPanelExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelExitMouseExited
        jPanelExit.setBackground(Color.black);
    }//GEN-LAST:event_jPanelExitMouseExited

    private void jPanelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jPanelExitMouseClicked
 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConversorGenerico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConversorGenerico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConversorGenerico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConversorGenerico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConversorGenerico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelExit;
    private javax.swing.JPanel jPanelExit;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JTextField textField1;
    private javax.swing.JTextField textField2;
    // End of variables declaration//GEN-END:variables
}
